# npx antora antora-playbook-home.yml
antora:
  extensions:
  - ./lib/noindex-extension.js
site:
  title: Eclipse Jetty
  url: https://jetty.org
content:
  sources:
  - url: .
    branches: HEAD
    start_path: home
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://github.com/webtide/jetty.website/releases/download/ui-prod-latest/ui-bundle.zip
    snapshot: true
output:
  dir: ./_site
